//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace agskeys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer_table
    {
        public int id { get; set; }
        public string name { get; set; }
        public string phoneno { get; set; }
        public string email { get; set; }
        public string address { get; set; }
        public string dob { get; set; }
        public string photo { get; set; }
        public string partnerid { get; set; }
        public string loantype { get; set; }
        public string bankname { get; set; }
        public string loanamount { get; set; }
        public string disbursementamount { get; set; }
        public string rateofintrest { get; set; }
        public string sanctioncopy { get; set; }
        public string idcopy { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string addedby { get; set; }
        public string datex { get; set; }
    }
}
