//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace agskeys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class emp_category_table
    {
        public int id { get; set; }
        public string emp_category { get; set; }
        public string status { get; set; }
        public string datex { get; set; }
        public string addedby { get; set; }
    }
}
