//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace agskeys.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;
    public partial class proof_table
    {
        [Key]
        public int id { get; set; }

        [Required(ErrorMessage = "Proofname is Required")]       
       // [Remote("UsernameExists", "Proofs", HttpMethod = "POST", ErrorMessage = "User name already registered.")]
        public string proofname { get; set; }

        public string porder { get; set; }
        public string status { get; set; }
        public string datex { get; set; }
        public string addedby { get; set; }
    }
}
